version: '3.9'

services:
  rucq:
    build: .
    ports:
      - "10015:10015"
      - "10016:10016"
      - "10017:10017"
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: rucqUser
      POSTGRES_DB: rucqDB
      POSTGRES_PASSWORD: kljk5lj46ioj4o6
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s  

