version: '3.9'

services:
  rucq:
    build: .
    ports:
      - "10015:10015"
      - "10017:10017"
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: rucqUser
      POSTGRES_DB: rucqDB
      POSTGRES_PASSWORD: kljk5lj46ioj4o6
    ports:
      - "5432:5432"


